config/routes.rb
Mappr::Application.routes.draw do

  root 'places#index'
  resources :places

end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

	def index
		@place = Place.last
	end

	def new
		# @place = Place.last
		@place = Place.new
	end

	def create
		@place = Place.create( place_params)
		redirect_to root_path
	end

	private
	def place_params
		params.require(:place).permit(:title, :address)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mappr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<h2>
	<%= link_to 'Mappr', root_path %>
	</h2>

	<%= link_to 'New +', new_place_path %>
	<hr/>
	
<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<h1> 
	Latest place Ladies & Gents
</h1>

<div>
	<% if @place.present? %>

		Title: <%= @place.title %>
		<br/>
		Address: <%= @place.address %>
		<br/>

		<script src="//maps.google.com/maps?file=api&amp;v=2&amp;key=AIzaSyDzleZt1Cn-Ha1cn19cC8LOKVFueX_iYB4"
            type="text/javascript"> </script>

      <script type="text/javascript">
    $(function() {


	$( window ).unload(function() {
		"Gunload()";
	});

      if (GBrowserIsCompatible()) {
        var map = new GMap2(document.getElementById("map_canvas"));
        map.setCenter(new GLatLng(37.4419, -122.1419), 13);
 
		var point = new GLatLng(37.4419, -122.1419);
	        map.addOverlay(new GMarker(point));

      }
    });

    </script>

 <div id="map_canvas" style="width: 500px; height: 300px"></div>

	<% else %>
		<h2> 
			Enter a place idiot. You fucked up! 
		</h2>

	<% end %>



</div>

app/views/places/new.html.erb
<h1>
	Enter a Place Please
</h1>

<div>
	<%= simple_form_for @place do |f| %>
	  	<%= f.input :title %>
	  	<%= f.input :address %>
	  	<%= submit_tag 'Lets Go Friend!' %>
	<% end %>

</div>